### ISSUE TITLE
Update to pm1.6 ASAP

### ISSUE THREAD

**Issue by kevin200** [Falkirks/DisguiseMe#21]
Please update this plugin to pm1.6 or pm1.5 asap.. I really need this plugin for API.

**Comment by Falkirks** [comment]
This plugin will be updated the PocketMine provides support for mobs.

**Comment by devin5411** [comment]
Hack the stuff in to make us happy!!!!!

**Comment by Falkirks** [comment]
@devin5411 It will be missing features that want and I doubt I will update it twice.
