### ISSUE TITLE
Allow us to rewrite DisguiseMe in Nukkit?

### ISSUE THREAD

**Issue by Snake1999** [Falkirks/DisguiseMe#26]
Hey Falk, 
I am Peter Jiang from FunCraft Team. We FunCraft are using Nukkit for our server in next generation. Nukkit is a Minecraft PE server software, we use it because it is written in Java , is more efficient and is able to carry thousands of players in one server. As our mini-games rewriting to adapt Nukkit, we need to rewrite  your DisguiseMe in Nukkit, and we will make it open-source in MIT License. Will you please you allow us?
Peter "DaMa" Jiang
26 Nov 2015

Note: For further information about Nukkit, visit https://github.com/Nukkit/Nukkit

**Comment by Falkirks** [comment]
The licensing on this project doesn't prevent you from doing that. You don't need any special permission from me.
