### ISSUE TITLE
Player ghost

### ISSUE THREAD

**Issue by Subtleoliver** [Falkirks/DisguiseMe#7]
When you disguise ourself other players kan see a ghost version of you at the place you disguised.

Pocketmine version: 1.4.1dev-938 「絶好(Zekkou)ケーキ(Cake)」 (Implementing API version 1.11.0 for Minecraft: PE v0.10.4 alpha protocol version 20)

**Comment by Falkirks** [comment]
Does it disappear when you end the disguise?

**Comment by Subtleoliver** [comment]
Note: Only other people can see the ghost and the disguised tag.

If you undisguise. the other player crashes.
